version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    command: npm run start:dev
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3001:3001'
    volumes:
      - ./frontend:/app
    command: npm start

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
