
name: CI/CD Tests - Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn build --if-present
      - run: yarn test
      - run: yarn prettier-check
      - run: yarn lint-check